name: flutter_base_master
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  #GetX状态管理框架 https://pub.flutter-io.cn/packages/get
  get: 4.6.1
  #toast https://pub.flutter-io.cn/packages/fluttertoast
  fluttertoast: 8.0.8
  # 网络请求库 https://github.com/flutterchina/dio
  dio: 4.0.4
  # lottie动画 https://pub.flutter-io.cn/packages/flutter_lottie
  lottie: 1.2.1
  # 网络检测 https://pub.flutter-io.cn/packages/connectivity
  connectivity: 3.0.6
  # SP键值对存储 https://pub.flutter-io.cn/packages/shared_preferences
  shared_preferences: 2.0.11
  #屏幕像素适配
  flutter_screenutil: 5.0.1+1
  #上拉刷新、下拉加载
  pull_to_refresh: 2.0.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^1.0.0
  lints: 1.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/lottie/


